# Customer and log analytics for a gamedev startup

Project Simulation: In this project, I took on the role of an analyst for a gamedev startup that launched a simple game on the market: in the app, users try to guess the answers to presented questions. The dataset consists of two datasets: user_data and logs.

Data Description:

user_data:  

client – user identifier  
premium – whether the client has premium status  
age – age  

logs:  
client – user identifier  
success – answer result (operation): success = 1, no = 0  
platform – platform  
time – time in Unix format

In [2]:
import pandas as pd

In [4]:
# define variables and read csv files
user_data = pd.read_csv('3_user_data.csv')
logs = pd.read_csv('3_logs.csv')

### Get some info from data

In [5]:
user_data.head()

   client  premium  age
0   46346    False   58
1    4391    False   55
2   27372    False   64
3   11989    False   44
4   60664    False   49

In [6]:
logs.head()

   client  success  platform        time
0   40177     True     phone  1585412212
1   61468     True     phone  1585425658
2   35604    False     phone  1585459894
3    9961     True     phone  1585400189
4   10931     True  computer  1585468629

In [7]:
print(f"Shape of user_data is {user_data.shape}")
print(f"------------------------------------")
print(f"Shape of user_data is {logs.shape}")

Shape of user_data is (2954, 3)
------------------------------------
Shape of user_data is (4500, 4)

In [8]:
user_data.describe()

             client          age
count   2954.000000  2954.000000
mean   50767.886594    44.196005
std    28800.505847    14.248336
min       40.000000    20.000000
25%    25639.500000    32.000000
50%    51569.500000    44.000000
75%    75963.250000    56.000000
max    99973.000000    69.000000

In [9]:
logs.describe()

             client          time
count   4500.000000  4.500000e+03
mean   50998.758000  1.585440e+09
std    28374.472495  2.314866e+04
min       40.000000  1.585400e+09
25%    27056.500000  1.585420e+09
50%    52659.000000  1.585440e+09
75%    76001.250000  1.585461e+09
max    99993.000000  1.585480e+09

In [10]:
user_data.dtypes

client     int64
premium     bool
age        int64
dtype: object

In [11]:
logs.dtypes

client       int64
success       bool
platform    object
time         int64
dtype: object

In [12]:
user_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2954 entries, 0 to 2953
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   client   2954 non-null   int64
 1   premium  2954 non-null   bool
 2   age      2954 non-null   int64
dtypes: bool(1), int64(2)
memory usage: 49.2 KB

In [13]:
logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   client    4500 non-null   int64
 1   success   4500 non-null   bool
 2   platform  4500 non-null   object
 3   time      4500 non-null   int64
dtypes: bool(1), int64(2), object(1)
memory usage: 110.0+ KB